EBT001: <0>は必須です。
EBT002: <0>は「<1>」文字以下で入力してください。（現在<2>文字）
EBT008: <0>は日付を正しく入力してください。
EBT004:	メールアドレスを正しく入力してください。
EBT016: メールアドレスまたは会員IDが間違っています。
EBT044: 解約予定日は契約終了日前を指定してください。
EBT019: すでにメールアドレスは登録されています。
EBT005:	<0>は半角英数で入力してください。
# EBT004 <=> EBT005
EBT023: パスワードは半角英数字記号で8～20文字で入力してください。
EBT025: パスワードには半角数字のみ、または半角英字のみの値は使用できません。
EBT030: 確認用のパスワードが間違っています。
EBT086: すでに証明書番号は登録されています。
EBT093: 登録・更新・削除処理に失敗しました。
EBT096: 登録・更新・削除処理に成功しました。
EBT010: <0>は数字を正しく入力してください。
EBT033: ファイル形式が誤っています。<0>を選択してください。
EBT034: ファイルのサイズ制限<0>を超えています。
EBT094: <0>が存在しておりません。
EBT095: インポートファイルの中身が正しくありません。
EBT092: インポートできました。
EBT036: <0>が取得できませんでした。
EBT090: 変更がありません